name: bidscube_sdk_flutter
description: "BidsCube Flutter SDK for displaying image, video, and native ads across all platforms."
version: 1.0.0
homepage: https://github.com/bidscube/bidscube-sdk-flutter

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.13.0
  video_player: ^2.10.0
  http: ^1.5.0
  xml: ^6.6.1
  package_info_plus: ^9.0.0
  device_info_plus: ^12.2.0
  interactive_media_ads: ^0.3.0+4
  video_player_android: ^2.8.17
  video_player_avfoundation: ^2.8.5
  video_player_platform_interface: ^6.6.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

example:
  path: example/

flutter:
  plugin:
    platforms:
      android:
        package: com.bidscube.sdk.flutter
        pluginClass: BidscubeSdkFlutterPlugin
      ios:
        pluginClass: BidscubeSdkPlugin
